{% set version = "4.9.2.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-plotly
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/plotly_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/plotly/plotly_{{ version }}.tar.gz
  sha256: f45eae325ab7e7924b0be098bad866ce003d657cf63e137104401c2dd4401db8

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-rcolorbrewer
    - r-base64enc
    - r-crosstalk
    - r-data.table
    - r-digest
    - r-dplyr
    - r-ggplot2 >=3.0.0
    - r-hexbin
    - r-htmltools >=0.3.6
    - r-htmlwidgets >=1.3
    - r-httr
    - r-jsonlite >=1.6
    - r-lazyeval >=0.2.0
    - r-magrittr
    - r-promises
    - r-purrr
    - r-rlang
    - r-scales
    - r-tibble
    - r-tidyr
    - r-viridislite
  run:
    - r-base
    - r-rcolorbrewer
    - r-base64enc
    - r-crosstalk
    - r-data.table
    - r-digest
    - r-dplyr
    - r-ggplot2 >=3.0.0
    - r-hexbin
    - r-htmltools >=0.3.6
    - r-htmlwidgets >=1.3
    - r-httr
    - r-jsonlite >=1.6
    - r-lazyeval >=0.2.0
    - r-magrittr
    - r-promises
    - r-purrr
    - r-rlang
    - r-scales
    - r-tibble
    - r-tidyr
    - r-viridislite

test:
  commands:
    - $R -e "library('plotly')"           # [not win]
    - "\"%R%\" -e \"library('plotly')\""  # [win]

about:
  home: https://plotly-r.com, https://github.com/ropensci/plotly#readme, https://plot.ly/r
  license: MIT
  summary: Create interactive web graphics from 'ggplot2' graphs and/or a custom interface to the (MIT-licensed) JavaScript library 'plotly.js' inspired by the grammar
    of graphics.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - halldc

# Package: plotly
# Title: Create Interactive Web Graphics via 'plotly.js'
# Version: 4.9.1
# Authors@R: c(person("Carson", "Sievert", role = c("aut", "cre"), email = "cpsievert1@gmail.com", comment = c(ORCID = "0000-0002-4958-2844")), person("Chris", "Parmer", role = "aut", email = "chris@plot.ly"), person("Toby", "Hocking", role = "aut", email = "tdhock5@gmail.com"), person("Scott", "Chamberlain", role = "aut", email = "myrmecocystus@gmail.com"), person("Karthik", "Ram", role = "aut", email = "karthik.ram@gmail.com"), person("Marianne", "Corvellec", role = "aut", email = "marianne.corvellec@igdore.org", comment = c(ORCID = "0000-0002-1994-3581")), person("Pedro", "Despouy", role = "aut", email = "pedro@plot.ly"), person("Plotly Technologies Inc.", role = "cph"))
# License: MIT + file LICENSE
# Description: Create interactive web graphics from 'ggplot2' graphs and/or a custom interface to the (MIT-licensed) JavaScript library 'plotly.js' inspired by the grammar of graphics.
# URL: https://plotly-r.com, https://github.com/ropensci/plotly#readme, https://plot.ly/r
# BugReports: https://github.com/ropensci/plotly/issues
# Depends: R (>= 3.2.0), ggplot2 (>= 3.0.0)
# Imports: tools, scales, httr, jsonlite (>= 1.6), magrittr, digest, viridisLite, base64enc, htmltools (>= 0.3.6), htmlwidgets (>= 1.3), tidyr, hexbin, RColorBrewer, dplyr, tibble, lazyeval (>= 0.2.0), rlang, crosstalk, purrr, data.table, promises
# Suggests: MASS, maps, ggthemes, GGally, testthat, knitr, devtools, shiny (>= 1.1.0), shinytest (>= 1.3.0), curl, rmarkdown, vdiffr, Cairo, broom, webshot, listviewer, dendextend, sf, maptools, rgeos, png, IRdisplay, processx, plotlyGeoAssets, forcats
# LazyData: true
# RoxygenNote: 6.1.1
# Encoding: UTF-8
# NeedsCompilation: no
# Packaged: 2019-11-07 17:19:06 UTC; cpsievert
# Author: Carson Sievert [aut, cre] (<https://orcid.org/0000-0002-4958-2844>), Chris Parmer [aut], Toby Hocking [aut], Scott Chamberlain [aut], Karthik Ram [aut], Marianne Corvellec [aut] (<https://orcid.org/0000-0002-1994-3581>), Pedro Despouy [aut], Plotly Technologies Inc. [cph]
# Maintainer: Carson Sievert <cpsievert1@gmail.com>
# Repository: CRAN
# Date/Publication: 2019-11-07 19:00:02 UTC
