{% set version = '4.8.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-plotly
  version: {{ version|replace("-", "_") }}

source:
  fn: plotly_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/plotly_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/plotly/plotly_{{ version }}.tar.gz
  sha256: 78f90282c831bbbb675ed4811fb506a98dd05e37251fabd42ebc263c80bae8a6

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 1000
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-rcolorbrewer
    - r-base64enc
    - r-crosstalk
    - r-data.table
    - r-digest
    - r-dplyr
    - r-ggplot2 >=3.0.0
    - r-hexbin
    - r-htmltools
    - r-htmlwidgets >=1.2
    - r-httr
    - r-jsonlite
    - r-lazyeval >=0.2.0
    - r-magrittr
    - r-promises
    - r-purrr
    - r-rlang
    - r-scales
    - r-tibble
    - r-tidyr
    - r-viridislite
  run:
    - r-base
    - r-rcolorbrewer
    - r-base64enc
    - r-crosstalk
    - r-data.table
    - r-digest
    - r-dplyr
    - r-ggplot2 >=3.0.0
    - r-hexbin
    - r-htmltools
    - r-htmlwidgets >=1.2
    - r-httr
    - r-jsonlite
    - r-lazyeval >=0.2.0
    - r-magrittr
    - r-promises
    - r-purrr
    - r-rlang
    - r-scales
    - r-tibble
    - r-tidyr
    - r-viridislite

test:
  commands:
    - $R -e "library('plotly')"           # [not win]
    - "\"%R%\" -e \"library('plotly')\""  # [win]

about:
  home: https://plot.ly/r, https://cpsievert.github.io/plotly_book/, https://github.com/ropensci/plotly#readme
  license: MIT
  summary: Easily translate 'ggplot2' graphs to an interactive web-based version and/or create
    custom web-based visualizations directly from R. Once uploaded to a 'plotly' account,
    'plotly' graphs (and the data behind them) can be viewed and modified in a web browser.
  license_family: MIT

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - halldc
